development:
  adapter: mysql2
  username: mmdb-fotoportal
  password: mmdb-fotoportal
  host: localhost
  database: mmdb-fotoportal

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  username: mmdb-fotoportal
  password: mmdb-fotoportal
  host: localhost
  database: mmdb-fotoportal
